# site settings
title: El Parque de la Bellota
subtitle: by Bellotita
email: youremailaddress@gmail.com
description: Este espacio une todos los recursos interactivos, mapas y actividades del <strong>Parque de la Bellota</strong>. Un lugar para aprender y divertirse.
baseurl: "/El-Parque-de-la-Bellota" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234
city: El Encinar del Alberche
state: Madrid
zip_code: 55555
country: Spain
phone: +34 123 456 789

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
